#
# PACKAGE
#
[package]
name = "status-server"
version = "3.0.0-beta.8"
edition = "2024"
publish = ["kellnr"]

[features]
# api/web "notifications"
api = ["default-components/api"]
websockets = ["default-components/websockets"]
frontend = ["default-components/frontend"]
# notifications
ntfy-notifications = ["default-components/ntfy-notifications"]
email-notifications = ["default-components/email-notifications"]
# status providers
dataminer-status = ["default-components/dataminer-status"]
minecraft-status = ["default-components/minecraft-status"]
website-status = ["default-components/website-status"]

# helper features
all-status = ["dataminer-status", "minecraft-status", "website-status"]
all-notifications = [
    "api", "websockets", "frontend",
    "email-notifications", "ntfy-notifications"
]
all = ["all-status", "all-notifications"]

default = ["all"]


[dependencies]
tracing = { workspace = true, features = ["release_max_level_info"]}
tracing-subscriber = { version = "0.3", features = ["parking_lot", "tracing-log"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
server.workspace = true
axum.workspace = true
default-components.workspace = true
clap = { version = "4.6", features = ["derive"] }
toml.workspace = true


#
# WORKSPACE
#
[workspace]
members = ["api-types","default-components", "frontend","server"]
resolver = "3"

[workspace.dependencies]
utils = { version = "0.5", registry = "kellnr", features = ["never"] }
default-components = { path = "default-components" }
api-types = { path = "api-types" }
tracing = "0.1"
axum = "0.8"
tokio = { version = "1.53", features = ["signal"] }
serde = { version = "1", features = ["derive"] }
parking_lot = "0.12"
chrono = "0.4"
toml = "1.1"
server = { path = "server" }
async-trait = "0.1"
bytecode = { version = "0.2", registry = "kellnr" }
