[package]
name = "api-types"
version = "3.0.0"
edition = "2024"

[features]
server-support = ["dep:server"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
server = { workspace = true, optional = true }
bytecode = { workspace = true, features = ["serde"] }
