name: Release

on:
    workflow_dispatch:
        inputs:
            release_notes:
                description: "Release notes for the GitHub tag"
                required: true
                default: ''

jobs:
    build_and_release:
        runs-on: ubuntu-latest
        env:
          TARGETS: "x86_64-unknown-linux-gnu"
        permissions:
          contents: write
        steps:
            # basic setup
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Install target toolchains
              run: rustup target add wasm32-unknown-unknown ${{ env.TARGETS }}
            - name: Install clippy
              run: rustup component add clippy

            # ensure that there are no issues with the code
            - name: Clippy check
              run: |
                mkdir -p static/wasm
                touch static/wasm/frontend.js static/wasm/frontend_bg.wasm
                cargo clippy --workspace --all-targets -- -D warnings
                cargo clippy --workspace --all-targets --all-features -- -D warnings
                cargo test --workspace --all-features
            - name: Tests
              run: cargo test --workspace

            # wasm-bindgen setup
            - name: Install wasm-bindgen-cli
              run: |
                  WG_VERSION=$(grep -m 1 'wasm-bindgen' frontend/Cargo.toml | sed -E 's/.*version = "([^"]+)".*/\1/' | sed -E 's/.*wasm-bindgen = "([^"]+)".*/\1/')
                  cargo install wasm-bindgen-cli --version $WG_VERSION

            # frontend building
            - name: Build frontend
              run: |
                  cargo build -p frontend --target wasm32-unknown-unknown --release
                  wasm-bindgen --target web --out-dir static/wasm --no-typescript --remove-name-section --remove-producers-section target/wasm32-unknown-unknown/release/frontend.wasm

            # build the backend
            - name: Build backend
              id: build_assets
              run: |
                FILES=""
                mkdir binaries
                for TARGET in $TARGETS; do
                  echo "=== Building $TARGET ==="
                  cargo build --release --target "$TARGET"
                
                  ASSET="binaries/status-server-$TARGET"
                  cp "target/$TARGET/release/status-server" "$ASSET"
                done

            # create the release
            - name: Get release Version
              run: |
                  VERSION=$(grep -m 1 '^version =' Cargo.toml | awk -F\" '{print $2}')
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v3
              with:
                  tag_name: v${{ env.VERSION }}
                  name: v${{ env.VERSION }}
                  body: ${{ inputs.release_notes }}
                  generate_release_notes: false
                  files: binaries/*
