name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Add neccessary files
        run: |
          mkdir -p static/wasm
          touch static/wasm/frontend.js static/wasm/frontend_bg.wasm

      - name: Run clippy on workspace
        run: cargo test --workspace --lib 
